controller_joint_names: ['', 'Joint_02', 'Joint_04', 'Joint_06', 'Joint_01', 'Joint_03', 'Joint_05', 'Joint_8', 'Joint_10', 'Joint_12', 'Joint_14', 'Joint_16', 'Joint_07', 'Joint_11', 'Joint_13', 'Joint_15', ]
